#!/usr/bin/env python3
from __future__ import annotations

import argparse
import tomllib
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate non-technical README.md from modpack/pack.toml"
    )
    parser.add_argument("--pack", default="modpack/pack.toml")
    parser.add_argument("--out", default="README.md")
    return parser.parse_args()


def read_toml(path: Path) -> dict:
    with path.open("rb") as f:
        data = tomllib.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a TOML table")
    return data


def display_name_for_category(key: str) -> str:
    return key.replace("_", " ").strip().title()


def item_name(item: dict) -> str:
    if isinstance(item.get("name"), str) and item["name"]:
        return item["name"]
    url = str(item.get("url", ""))
    return url.rstrip("/").split("/")[-1]


def item_link(item: dict) -> str:
    return str(item.get("url", "")).strip()


def side_label(side: str) -> str:
    if side == "client":
        return "Client"
    if side == "server":
        return "Server"
    return "Both"


def render_section_lines(top: dict, list_key: str) -> list[str]:
    lines: list[str] = []
    for category, raw in top.items():
        if not isinstance(raw, dict):
            continue
        entries = raw.get(list_key)
        if not isinstance(entries, list) or not entries:
            continue
        lines.append(f"### {display_name_for_category(category)}")
        lines.append("")
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            name = item_name(entry)
            url = item_link(entry)
            side = side_label(str(entry.get("side", "both")))
            lines.append(f"- [{name}]({url}) ({side})")
        lines.append("")
    if not lines:
        lines.append("- None configured")
        lines.append("")
    return lines


def build_readme(data: dict) -> str:
    pack = data.get("pack")
    deps = data.get("dependencies")
    if not isinstance(pack, dict) or not isinstance(deps, dict):
        raise ValueError("pack.toml must include [pack] and [dependencies]")

    pack_name = str(pack.get("name", "Modpack"))
    summary = str(pack.get("summary", ""))
    minecraft = str(deps.get("minecraft", ""))
    loader = str(deps.get("loader", ""))
    loader_version = str(deps.get("loader_version", ""))

    mods = data.get("mods")
    resourcepacks = data.get("resourcepacks")
    shaderpacks = data.get("shaderpacks")

    mod_count = 0
    if isinstance(mods, dict):
        for raw in mods.values():
            if isinstance(raw, dict) and isinstance(raw.get("mods"), list):
                mod_count += len(raw["mods"])

    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by scripts/generate_readme.py from modpack/pack.toml -->")
    lines.append(f"# {pack_name}")
    lines.append("")
    if summary:
        lines.append(summary)
        lines.append("")

    lines.append("## Download and play")
    lines.append("")
    lines.append("1. Go to this repository's GitHub Releases page.")
    lines.append("2. Download the latest `chuj-client-<version>.mrpack`.")
    lines.append("3. Open Prism Launcher.")
    lines.append("4. Click `Add Instance` -> `Import`.")
    lines.append("5. Select the downloaded `.mrpack` file.")
    lines.append("")
    lines.append("Use `chuj-server-<version>.mrpack` for dedicated server setup.")
    lines.append("")

    lines.append("## Pack info")
    lines.append("")
    lines.append(f"- Minecraft: `{minecraft}`")
    lines.append(f"- Loader: `{loader.title()} {loader_version}`")
    lines.append(f"- Total mods: `{mod_count}`")
    lines.append("")

    lines.append("## Included mods")
    lines.append("")
    if isinstance(mods, dict):
        lines.extend(render_section_lines(mods, "mods"))
    else:
        lines.append("- None configured")
        lines.append("")

    lines.append("## Resource packs")
    lines.append("")
    if isinstance(resourcepacks, dict):
        lines.extend(render_section_lines(resourcepacks, "packs"))
    else:
        lines.append("- None configured")
        lines.append("")

    lines.append("## Shader packs")
    lines.append("")
    if isinstance(shaderpacks, dict):
        lines.extend(render_section_lines(shaderpacks, "packs"))
    else:
        lines.append("- None configured")
        lines.append("")

    lines.append("## Project docs")
    lines.append("")
    lines.append("- Maintainer guide: `README.maintainers.md`")
    lines.append("- Pack source of truth: `modpack/pack.toml`")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    data = read_toml(Path(args.pack))
    out_text = build_readme(data)

    out_path = Path(args.out)
    out_path.write_text(out_text, encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
